#!/bin/bash

#BSUB -q gpu
#BSUB -W 02:00
#BSUB -J parallel-test
#BSUB -o %J.stdout
#BSUB -e %J.stderr
#BSUB -gpu "num=1:mode=shared:mps=no:j_exclusive=no"
#BSUB -n 4
#BSUB -R "span[ptile=32]"

# module load deepmd/2.0

module load miniconda3/base
source activate band-alignment
module load gcc/7.5.0

python pmda_hb.py
